apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: jenkins-persistent
  name: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: glusterfs-apps
