apiVersion: v1
kind: Template
labels:
  template: tf-base-notebook-builder
metadata:
  annotations:
    description: tf-base-notebook container
    iconClass: tensorflow
    tags: ai-stack-builder
  name: tf-base-notebook-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: tf-base-notebook
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: tf-base-notebook
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tf-base-notebook:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: tf-base-notebook
          - name: BUILD_LOGLEVEL
            value: "2"
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/radanalyticsio/tf-base-notebook.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: ""
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master